version: '3'
services:
  olivia-ai.org:
    image: "docker.pkg.github.com/NerdDoc/server-ai.org/olivia-ai.org:latest"
    build:
      context: .
      args:
        - VUE_APP_URL=ws://localhost:8080
    environment:
      - PORT=80
    ports:
      - "80:80"
  olivia:
    image: "docker.pkg.github.com/NerdDoc/server/olivia:latest"
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
